spring:

  jpa:
    show-sql: true
    properties.hibernate.format_sql: true
    generate-ddl: true
    hibernate.ddl-auto: update
    properties.hibernate.jdbc.lob.non_contextual_creation: true
logging.level.org.hibernate.type: trace
